<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Welcome extends CI_Controller
{

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see https://codeigniter.com/user_guide/general/urls.html
	 */
	public function index()
	{
		redirect(base_url());
		$this->load->view('welcome_message');
	}

	public function php_info()
	{
		phpinfo();
	}

	public function pdf()
	{
		$this->load->library('PdfGenerator');
		$html = $this->load->view('welcome_message', '$data', true);

		$this->pdfgenerator->generate($html, 'contoh', true, 'F4', 'landscape');
	}

	public function test_api()
	{
		// $this->load->library('encryption','encrypt');
		// $decrypt = $this->encrypt->decode($this->input->cookie('jss_session', false),"diskominfo");

		// die(json_encode($decrypt));
		$data = file_get_contents('https://webservice.jogjakota.go.id/jss/akun?id=JSS-A4562');
		die($data);
	}

	public function test_login()
	{
		$this->load->library('curl');
		$parameter = json_encode(array('username' => 'fajar', 'password' => 'setya'));
		$data = $this->curl->simple_post('https://layananupik.jogjakota.go.id/lumen/public/api/login', $parameter);
		die($data);
	}

	public function  test_jss_cookie()
	{
		//https://jss.jogjakota.go.id/
		$this->load->helper('cookie');



		// array
		// $decrypt = $this->encrypt->decode($this->input->cookie('jss_session', false),"diskominfo");
		// die($decrypt);
	}

	public function export_excel()
	{
		$this->load->library("Excel/PHPExcel");

		// Create Objek phpExcel
		$objPHPExcel = new PHPExcel();

		$objPHPExcel->getProperties()->setCreator("KIB")
			->setLastModifiedBy("KIB")
			->setTitle("Export Data KIB")
			->setSubject("Export KIB To Excel")
			->setDescription("Doc for Office 2007 XLSX, generated by PHPExcel.")
			->setKeywords("office 2007 openxml php")
			->setCategory("PHPExcel");
		$objPHPExcel->getActiveSheet()->setTitle('Data KIB');

		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		header('Last-Modified:' . gmdate("D, d M Y H:i:s") . 'GMT');
		header('Chace-Control: no-store, no-cache, must-revalation');
		header('Chace-Control: post-check=0, pre-check=0', false);
		header('Pragma: no-cache');
		header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
		header('Content-Disposition: attachment;filename="Export Data KIB ' . date('Y-m-d') . '.xlsx"');

		$objWriter->save('php://output');
		die();
	}

	public function import_csv()
	{
		// Load plugin PHPExcel nya
		// include APPPATH . 'third_party/PHPExcel/PHPExcel.php';
		include APPPATH . 'libraries/Excel/PHPExcel.php';
		$filename = "kib_a"; // Kita tentukan nama filenya

		$csvreader = PHPExcel_IOFactory::createReader('CSV')->setDelimiter("\t");
		$loadcsv = $csvreader->load('assets/files/migrasi_upload/' . $filename . '.csv'); // Load file yang tadi diupload ke folder csv
		// $loadcsv = $csvreader->load('assets/files/migrasi_upload/' . $filename . '.xlsx'); // Load file yang tadi diupload ke folder xlsx
		$sheet = $loadcsv->getActiveSheet()->getRowIterator();

		// Buat sebuah variabel array untuk menampung array data yg akan kita insert ke database
		$data = array();

		$numrow = 1;
		// die(json_encode($sheet));
		foreach ($sheet as $row) {
			// Cek $numrow apakah lebih dari 1
			// Artinya karena baris pertama adalah nama-nama kolom
			// Jadi dilewat saja, tidak usah diimport
			if ($numrow > 1) {
				// START -->
				// Skrip untuk mengambil value nya
				$cellIterator = $row->getCellIterator();
				$cellIterator->setIterateOnlyExistingCells(false); // Loop all cells, even if it is not set

				$get = array(); // Valuenya akan di simpan kedalam array,dimulai dari index ke 0
				foreach ($cellIterator as $cell) {
					array_push($get, $cell->getValue()); // Menambahkan value ke variabel array $get
				}
				// <-- END
				// die(json_encode($get));
				/*
				// Ambil data value yang telah di ambil dan dimasukkan ke variabel $get
				$nis = $get[0]; // Ambil data NIS dari kolom A di csv
				$nama = $get[1]; // Ambil data nama dari kolom B di csv
				$jenis_kelamin = $get[2]; // Ambil data jenis kelamin dari kolom C di csv
				$alamat = $get[3]; // Ambil data alamat dari kolom D di csv

				// Kita push (add) array data ke variabel data
				array_push($data, array(
					'nis' => $nis, // Insert data nis
					'nama' => $nama, // Insert data nama
					'jenis_kelamin' => $jenis_kelamin, // Insert data jenis kelamin
					'alamat' => $alamat, // Insert data alamat
				));
				*/
				array_push($data, array(
					"Id_Inventaris"	=> isset($get[0]) ? $get[0] : null,
					"Permendagri_90"	=>	isset($get[1]) ? $get[1] : null,
					"Nama_Barang_Permendagri_90" => isset($get[2]) ? $get[2] : null,
					"No_Kode_Barang" => isset($get[3]) ? $get[3] : null,
					"Nama_Sesuai Kode" => isset($get[4]) ? $get[4] : null,
					"Nama_Simbada" => isset($get[5]) ? $get[5] : null,
					"Luas_Tanah" => isset($get[6]) ? $get[6] : null,
					"Thn_Pengadaan"	=> isset($get[7]) ? $get[7] : null,
					"Letak" => isset($get[8]) ? $get[8] : null,
					"Hak_Tanah"	=> isset($get[9]) ? $get[9] : null,
					"Tgl_Sertifikat" => isset($get[10]) ? $get[10] : null,
					"No_Sertifikat" => isset($get[11]) ? $get[11] : null,
					"Penggunaan"	=> isset($get[12]) ? $get[12] : null,
					"Asal_Usul" => isset($get[13]) ? $get[13] : null,
					"Harga_Barang" => isset($get[14]) ? $get[14] : null,
					"Keterangan"	=> isset($get[15]) ? $get[15] : null,
					"Kode_SKPD"	=> isset($get[16]) ? $get[16] : null,
					"Nama_SKPD"	=> isset($get[17]) ? $get[17] : null,
					"Kode_Lokasi"	=> isset($get[18]) ? $get[18] : null,
					"Nama_Lokasi"	=> isset($get[19]) ? $get[19] : null,
				));
			}

			$numrow++; // Tambah 1 setiap kali looping
		}
		die(json_encode($data));
		/*
		// Panggil fungsi insert_multiple yg telah kita buat sebelumnya di model
		$this->SiswaModel->insert_multiple($data);

		redirect("Siswa"); // Redirect ke halaman awal (ke controller siswa fungsi index)
		*/
	}
}
