<?php

if (!defined('BASEPATH')) exit('No direct script access allowed');

class Global_mutasi extends CI_Controller
{
  function __construct()
  {
    parent::__construct();
    $this->load->model('pengajuan_model');
    $this->load->library('form_validation');
    $this->load->library('datatables');
    $this->load->helper('my_global');
    $this->load->model('User_model');
    $this->load->model('Global_mutasi_model', 'mutasi_model');
  }

  public function json_kib_a($pihak = null)
  {
    header('Content-Type: application/json');
    $list_id_kib_a = $this->input->post('list_id_kib_a');
    echo $this->mutasi_model->json_kib_a($pihak, $list_id_kib_a);
  }

  public function json_kib_b($pihak = null)
  {
    header('Content-Type: application/json');
    $list_id_kib_b = $this->input->post('list_id_kib_b');
    // die(json_encode($list_id_kib_b));
    echo $this->mutasi_model->json_kib_b($pihak, $list_id_kib_b);
  }

  public function json_kib_c($pihak = null)
  {
    header('Content-Type: application/json');
    $list_id_kib_c = $this->input->post('list_id_kib_c');
    echo $this->mutasi_model->json_kib_c($pihak, $list_id_kib_c);
  }

  public function json_kib_d($pihak = null)
  {
    header('Content-Type: application/json');
    $list_id_kib_d = $this->input->post('list_id_kib_d');
    echo $this->mutasi_model->json_kib_d($pihak, $list_id_kib_d);
  }

  public function json_kib_e($pihak = null)
  {
    header('Content-Type: application/json');
    $list_id_kib_e = $this->input->post('list_id_kib_e');
    echo $this->mutasi_model->json_kib_e($pihak, $list_id_kib_e);
  }

  public function json_kib_f($pihak = null)
  {
    header('Content-Type: application/json');
    $list_id_kib_f = $this->input->post('list_id_kib_f');
    echo $this->mutasi_model->json_kib_f($pihak, $list_id_kib_f);
  }

  public function json_kib_atb($pihak = null)
  {
    header('Content-Type: application/json');
    $list_id_kib_atb = $this->input->post('list_id_kib_atb');
    echo $this->mutasi_model->json_kib_atb($pihak, $list_id_kib_atb);
  }

  function update_mutasi($id_mutasi, $data)
  {
    $this->db->where('id_mutasi', $id_mutasi);
    $this->db->update('tbl_mutasi', $data);
  }
}

/* End of file Usulan.php */
/* Location: ./application/controllers/Usulan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-24 05:56:49 */
/* http://harviacode.com */
