<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Kapitalisasi_model extends CI_Model{

  public $table = 'tbl_master_kapitalisasi';
  public $id = 'Kelompok_Manfaat';
  public $order = 'DESC';

  function __construct()
  {
    parent::__construct();
  }

  // datatables
  function json() {
    $this->datatables->select('Kelompok_Manfaat, Bidang_Barang, Batas_A, Batas_B, Batas_C, Batas_D, Batas_E, Batas_F, Tambah_A, Tambah_B, Tambah_C, Tambah_D, Tambah_E');
    $this->datatables->from('tbl_master_kapitalisasi');
    //add this line for join
    //$this->datatables->join('table2', 'tbl_kode_barang.field = table2.field');
    $this->datatables->add_column('action', anchor(base_url('master_data/kapitalisasi/update/$1'),'<span class="fa fa-edit" style="font-size:18px;"></span>')." &nbsp ".anchor(base_url('master_data/kapitalisasi/delete/$1'),'<span class="fa fa-trash" style="font-size:18px;"></span>','onclick="javasciprt: return confirm(\'Yakin Ingin Mengahapus ?\')"'), 'Kelompok_Manfaat');
    return
    $this->datatables->generate();
    // die($this->db->last_query());
  }

  // get all
  function get_all()
  {
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row();
  }
/*
  // get total rows
  function total_rows($q = NULL) {
    $this->db->like('id_kode_barang', $q);
    $this->db->or_like('kode_barang', $q);
    $this->db->or_like('nama_barang', $q);
    $this->db->or_like('akun', $q);
    $this->db->or_like('rincian_objek', $q);
    $this->db->or_like('jenis', $q);
    $this->db->or_like('objek', $q);
    $this->db->or_like('rincian_objek', $q);
    $this->db->or_like('sub_rincian_objek', $q);
    $this->db->or_like('sub_sub_rincian_objek', $q);
    $this->db->or_like('umur_ekonomis', $q);
    $this->db->or_like('nilai_residu', $q);
    $this->db->or_like('rincian_objek_manfaat', $q);
    $this->db->from($this->table);
    return $this->db->count_all_results();
  }

  // get data with limit and search
  function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_kode_barang', $q);
    $this->db->or_like('kode_barang', $q);
    $this->db->or_like('nama_barang', $q);
    $this->db->or_like('akun', $q);
    $this->db->or_like('rincian_objek', $q);
    $this->db->or_like('jenis', $q);
    $this->db->or_like('objek', $q);
    $this->db->or_like('rincian_objek', $q);
    $this->db->or_like('sub_rincian_objek', $q);
    $this->db->or_like('sub_sub_rincian_objek', $q);
    $this->db->or_like('umur_ekonomis', $q);
    $this->db->or_like('nilai_residu', $q);
    $this->db->or_like('rincian_objek_manfaat', $q);
    $this->db->limit($limit, $start);
    return $this->db->get($this->table)->result();
  }
*/
  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

  function get_bidang_barang(){
    return $this->db->get('view_kode_barang_rincian_objek')->result();
  }

}

/* End of file Kode_barang_model.php */
/* Location: ./application/models/Kode_barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-19 06:22:01 */
/* http://harviacode.com */
