<?php

if (!defined('BASEPATH'))
  exit('No direct script access allowed');

class Kode_lokasi_model extends CI_Model
{

  public $table = 'tbl_kode_lokasi';
  public $id = 'id_kode_lokasi';
  public $order = 'DESC';

  function __construct()
  {
    parent::__construct();
  }

  // datatables
  function json()
  {
    $this->datatables->select('id_kode_lokasi,intra_kom_ekstra_kom,propinsi,kabupaten
      ,pengguna,pengguna_urusan_unsur,pengguna_bidang,pengguna_opd
      ,kuasa_pengguna,sub_kuasa_pengguna,instansi,keterangan');
    $this->datatables->from('tbl_kode_lokasi');
    $this->datatables->where('length(pengguna)', 6);
    //add this line for join
    //$this->datatables->join('table2', 'tbl_kode_lokasi.field = table2.field');
    // $this->datatables->add_column('action', anchor(base_url('kode_lokasi/read/$1'),'Read')." | ".anchor(base_url('kode_lokasi/update/$1'),'Update')." | ".anchor(base_url('kode_lokasi/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_kode_lokasi');
    $this->datatables->add_column('action', anchor(base_url('master_data/kode_lokasi/update/$1'), '<span class="fa fa-edit" style="font-size:18px;"></span>') . " &nbsp " . anchor(base_url('master_data/kode_lokasi/delete/$1'), '<span class="fa fa-trash" style="font-size:18px;"></span>', 'onclick="javasciprt: return confirm(\'Yakin Ingin Mengahapus ?\')"'), 'id_kode_lokasi');
    $this->db->order_by('kode_lokasi');
    return
      $this->datatables->generate();
    // die($this->db->last_query());
  }

  // get all
  function get_all()
  {
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row();
  }

  // get total rows
  function total_rows($q = NULL)
  {
    $this->db->like('id_kode_lokasi', $q);
    $this->db->or_like('intra_kom_ekstra_kom', $q);
    $this->db->or_like('propinsi', $q);
    $this->db->or_like('kabupaten', $q);
    $this->db->or_like('pengguna', $q);
    $this->db->or_like('kuasa_pengguna', $q);
    $this->db->or_like('sub_kuasa_pengguna', $q);
    $this->db->or_like('instansi', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->from($this->table);
    return $this->db->count_all_results();
  }

  // get data with limit and search
  function get_limit_data($limit, $start = 0, $q = NULL)
  {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_kode_lokasi', $q);
    $this->db->or_like('intra_kom_ekstra_kom', $q);
    $this->db->or_like('propinsi', $q);
    $this->db->or_like('kabupaten', $q);
    $this->db->or_like('pengguna', $q);
    $this->db->or_like('kuasa_pengguna', $q);
    $this->db->or_like('sub_kuasa_pengguna', $q);
    $this->db->or_like('instansi', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->limit($limit, $start);
    return $this->db->get($this->table)->result();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }
}

/* End of file Kode_lokasi_model.php */
/* Location: ./application/models/Kode_lokasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-19 06:22:19 */
/* http://harviacode.com */
