<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Tanda_tangan_model extends CI_Model
{

  public $table = 'tbl_tanda_tangan';
  public $id = 'id_tanda_tangan';
  public $order = 'DESC';

  function __construct()
  {
    parent::__construct();
  }

  // datatables
  function json() {
    $this->load->helper('my_datatable');
    $session = $this->session->userdata('session');
    // $this->datatables->select("A.id_kode_lokasi,D.kode_lokasi, D.instansi,group_concat(concat_ws(' : ',B.description, C.nama)) as tanda_tangan");
    // $this->datatables->from('tbl_tanda_tangan as A');
    // $this->datatables->join('tbl_master_jabatan as B','A.id_jabatan=B.id_jabatan','left');
    // $this->datatables->join('tbl_user C','A.id_user=C.id_user','left');
    // $this->datatables->join('view_lokasi as D','A.id_kode_lokasi=D.id_kode_lokasi','left');
    // $this->datatables->group_by('A.id_kode_lokasi');
    $this->datatables->select("id_kode_lokasi, kode_lokasi, instansi, tanda_tangan, lokasi");
    $this->datatables->from(
      "(SELECT A.id_kode_lokasi,D.kode_lokasi,D.pengguna, D.instansi,group_concat(concat_ws(' : ',B.description, C.nama)) as tanda_tangan, concat_ws('-',D.kode_lokasi, D.instansi) as lokasi
      FROM `tbl_tanda_tangan` `A`
      LEFT JOIN `tbl_master_jabatan` `B` ON `A`.`id_jabatan`=`B`.`id_jabatan`
      LEFT JOIN `tbl_user` `C` ON `A`.`id_user`=`C`.`id_user`
      LEFT JOIN `view_lokasi` `D` ON `A`.`id_kode_lokasi`=`D`.`id_kode_lokasi`
      GROUP BY `A`.`id_kode_lokasi`) as A1"
      );
      
    $lokasi = explode('.', $session->kode_lokasi);
    $pengguna = $lokasi[3];
    
    if($session->id_role != 1){
      $this->db->where('pengguna', $pengguna);
    }
    $this->datatables->edit_column('lokasi','$1 - $2','remove_star(kode_lokasi), instansi');
    // $this->datatables->edit_column('instansi','$1 - $2','remove_star(kode_lokasi), instansi');
    $this->datatables->edit_column('tanda_tangan','$1','list_tanda_tangan(tanda_tangan)');
    $this->datatables->add_column('action', anchor(base_url('master_data/tanda_tangan/update/$1'),'<span class="fa fa-edit" style="font-size:18px;"></span>')." &nbsp ".anchor(base_url('master_data/tanda_tangan/delete_by_kode_lokasi/$1'),'<span class="fa fa-trash" style="font-size:18px;"></span>','onclick="javasciprt: return confirm(\'Yakin Ingin Mengahapus ?\')"'), 'id_kode_lokasi');
    return
    $this->datatables->generate();
    // die($this->db->last_query());
  }

  function insert_batch($data){
    $this->db->insert_batch($this->table, $data);
  }


  function get_axist_lokasi($id_kode_lokasi)
  {
    $this->db->select('A.id_kode_lokasi,B.kode_lokasi');
    $this->db->from($this->table.' A');
    $this->db->join('view_lokasi B','A.id_kode_lokasi=B.id_kode_lokasi','left');
    $this->db->where('A.id_kode_lokasi', $id_kode_lokasi);
    $this->db->group_by('A.id_kode_lokasi,B.kode_lokasi');
    return $this->db->get()->row();
  }


  function tanda_tangan($id_kode_lokasi)
  {
    $this->db->select('*');
    $this->db->where('id_kode_lokasi', $id_kode_lokasi);
    return $this->db->get($this->table)->result();
  }

  // delete data
  function delete_by_kode_lokasi($id_kode_lokasi){
    $this->db->where('id_kode_lokasi', $id_kode_lokasi);
    $this->db->delete($this->table);
  }

  function getLokasi(){
    $session = $this->session->userdata('session');
    $temp_kode_lokasi = explode('.',$session->kode_lokasi);
    $this->db->select('id_kode_lokasi,CONCAT(intra_kom_ekstra_kom,".",propinsi,".",kabupaten,".",pengguna,".",kuasa_pengguna,".",sub_kuasa_pengguna) AS kode, instansi');
    $this->db->from('tbl_kode_lokasi');

    if ($session->id_role != 1)
      $this->db->where('pengguna',$temp_kode_lokasi[3]);

    $this->db->where('char_length(pengguna) >= ',6);

    $this->db->order_by('kode', 'ASC');
    return $this->db->get()->result();
  }

  function getUser($kode_lokasi){
    $arr_kode_lokasi = explode('.',$kode_lokasi);
    $this->db->select('A.*');
    $this->db->from('tbl_user A');
    $this->db->join('tbl_kode_lokasi B','A.id_kode_lokasi=B.id_kode_lokasi','left');
    $this->db->where('B.pengguna',$arr_kode_lokasi[3]);
    $this->db->order_by('id_user', 'ASC');
    return $this->db->get()->result();
  }

}

/* End of file Tanda_tangan_model.php */
/* Location: ./application/models/Tanda_tangan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-19 06:22:19 */
/* http://harviacode.com */
