<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Master_rekening_model extends CI_Model
{

  public $table = 'tbl_master_rekening';
  public $id = 'id_master_rekening';
  public $order = 'DESC';

  function __construct()
  {
    parent::__construct();
  }

  // datatables
  function json() {
    $this->datatables->select('id_rekening,sumber_dana,kode_rekening,nama_rekening');
    $this->datatables->from('vtbl_master_rekening');
    //$this->datatables->where('is_remove="1"');
    //add this line for join
    //$this->datatables->join('table2', 'tbl_master_rekening.field = table2.field');
    // $this->datatables->add_column('action', anchor(base_url('master_rekening/read/$1'),'Read')." | ".anchor(base_url('master_rekening/update/$1'),'Update')." | ".anchor(base_url('master_rekening/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_master_rekening');
    $this->datatables->add_column('action',anchor(base_url('master_data/master_rekening/update/$1'),'<span class="fa fa-edit" style="font-size:18px;"></span>')
                                ." &nbsp ".anchor(base_url('master_data/master_rekening/delete/$1'),'<span class="fa fa-trash" style="font-size:18px;"></span>','onclick="javasciprt: return confirm(\'Yakin Ingin Mengahapus ?\')"'), 'id_rekening');
    return $this->datatables->generate();
  }
  
  function get_sumber_dana()
  {
    return $this->db->get('tbl_master_sumber_dana')->result_array();
  }

  // get all
  function get_all()
  {
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where('id_rekening', $id);
    return $this->db->get($this->table)->row();
  }

  // get total rows
  function total_rows($q = NULL) {
    $this->db->like('id_rekening', $q);
    $this->db->or_like('id_sumber_dana', $q);
    $this->db->or_like('kode_rekening', $q);
    $this->db->or_like('nama_rekening', $q);
    $this->db->from($this->table);
    return $this->db->count_all_results();
  }

  // get data with limit and search
  function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_rekening', $q);
    $this->db->or_like('id_sumber_dana', $q);
    $this->db->or_like('kode_rekening', $q);
    $this->db->or_like('nama_rekening', $q);
    $this->db->limit($limit, $start);
    return $this->db->get($this->table)->result();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where('id_rekening', $id);
    $this->db->update($this->table, $data);
  }

  // delete data
  /*
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }
  */
  function delete($id)
  {
    $this->db->where('id_rekening', $id);
    $this->db->update($this->table);
  }


}

/* End of file Master_rekening_model.php */
/* Location: ./application/models/Master_rekening_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-16 06:26:02 */
/* http://harviacode.com */
