<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Login_model extends CI_Model{

  public $table = 'tbl_user';
  public $tbl_hak_akses = 'tbl_hak_akses';
  public $tbl_menu = 'tbl_menu';
  public $tbl_kode_lokasi = 'tbl_kode_lokasi';
  public $view_lokasi = 'view_lokasi';

  public $nip = 'nip';
  public $order = 'DESC';

  function __construct(){
    parent::__construct();
  }

  // get data by id
  function get_by_nip($nip){
    $this->db->where($this->nip, $nip);
    return $this->db->get($this->table)->row();
  }


  function get_user_by_id($id){
    $this->db->where('id_user', $id);
    $this->db->join('tbl_role B','A.id_role=B.id_role','left');
    return $this->db->get('tbl_user A')->row();
  }

  function get_by_id_upik($id_upik){
    $this->db->select('A.* , B.list_id_menu, C.kode_lokasi, C.instansi as nama_lokasi, R.description as role');
    $this->db->from($this->table.' A');
    $this->db->join("(SELECT id_role, group_concat(id_menu) list_id_menu
	                   FROM tbl_hak_akses A
	                   where active = 'y'
                     group by id_role) B" ,'A.id_role = B.id_role','left' );
    $this->db->join($this->view_lokasi.' C','A.id_kode_lokasi=C.id_kode_lokasi','left');
    $this->db->join('tbl_role R','A.id_role=R.id_role','left');
    $this->db->where('A.id_upik', $id_upik);
    return
    $this->db->get()->row();
    // die($this->db->last_query());
  }

  function get_menu($id_role){
    $this->db->distinct()
          ->select('B.menu')
          ->from($this->tbl_hak_akses.' A')
          ->join($this->tbl_menu.' B', 'A.id_menu=B.id_menu', 'left')
          ->where('A.active' , 'y')
          ->where('A.id_role' , $id_role);
    return
    $this->db->get()->result();
    // die($this->db->last_query());
  }

  function get_sub_menu($id_role){
    $this->db->select('A.id_hak_akses, A.id_menu, B.menu, B.sub_menu, B.url')
          ->from($this->tbl_hak_akses.' A')
          ->join($this->tbl_menu.' B', 'A.id_menu=B.id_menu', 'left')
          ->where('A.active' , 'y')
          ->where('A.id_role' , $id_role);
    return $this->db->get()->result();
  }


}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-09 06:17:03 */
/* http://harviacode.com */
