<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class User_model extends CI_Model{

  public $table = 'tbl_user';
  public $tbl_lokasi = 'tbl_kode_lokasi';
  public $id = 'id_user';
  public $order = 'DESC';

  function __construct(){
    parent::__construct();
  }

  // datatables
  function json() {
    $session = $this->session->userdata('session');
    $this->load->helper('my_datatable');
   $this->datatables->select("A.id_user, A.nama, A.nip, A.nik, B.kode_lokasi, B.instansi, C.description as role_desc, D.description as jabatan_desc,case when A.freze = '1' then 'Ya' when A.freze = '0' then 'Tidak' end as status_freze,A.freze");
    $this->datatables->from($this->table.' A');
    //add this line for join
    $this->datatables->join('view_lokasi B', 'A.id_kode_lokasi = B.id_kode_lokasi', 'left');
    $this->datatables->join('tbl_role C', 'A.id_role = C.id_role', 'left');
    $this->datatables->join('tbl_master_jabatan D', 'A.id_jabatan = D.id_jabatan', 'left');

    if ($session->id_role != 1)
      $this->datatables->where('C.id_role <> ', 1);
    $this->datatables->add_column('action', anchor(base_url('User/update/$1'),'Perbarui', array('class' => 'btn btn-sm btn-primary'))." | ".anchor(base_url('User/delete/$1'),'Hapus','class="btn btn-sm btn-danger" onclick="javasciprt: return confirm(\'Yakin Ingin Menghapus ?\')"'), 'id_user');
    $this->datatables->add_column('lokasi','$1 - $2' , 'remove_star(kode_lokasi), instansi');
    return
    $this->datatables->generate();
    // die($this->db->last_query());
  }

  // get all
  function get_all()
  {
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  // get data by id
  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row();
  }

  // get total rows
  function total_rows($q = NULL) {
    $this->db->like('id_user', $q);
    $this->db->or_like('nama', $q);
    $this->db->or_like('nip', $q);
    $this->db->or_like('kode_lokasi', $q);
    $this->db->from($this->table);
    return $this->db->count_all_results();
  }

  // get data with limit and search
  function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_user', $q);
    $this->db->or_like('nama', $q);
    $this->db->or_like('nip', $q);
    $this->db->or_like('kode_lokasi', $q);
    $this->db->limit($limit, $start);
    return $this->db->get($this->table)->result();
  }

  // insert data
  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
  }

  // delete data
  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

  function getLokasi(){
    $session = $this->session->userdata('session');
    $temp_kode_lokasi = explode('.',$session->kode_lokasi);
    $this->db->select('id_kode_lokasi,CONCAT(intra_kom_ekstra_kom,".",propinsi,".",kabupaten,".",pengguna,".",kuasa_pengguna,".",sub_kuasa_pengguna) AS kode, instansi');
    $this->db->from('tbl_kode_lokasi');
    // die(json_encode($session));
    if ($session->id_role != 1)
      $this->db->where('pengguna',$temp_kode_lokasi[3]);
    $this->db->where('char_length(pengguna) >= ',6);  
    $this->db->order_by('kode', 'ASC');
    return $this->db->get()->result();
  }

  function getRole(){
    return $this->db->get('tbl_role')->result();
  }

  function getJabatan(){
    return $this->db->get('tbl_master_jabatan')->result();
  }

  function get_by_id_upik($id_upik){
    return $this->db->get_where($this->table,array('id_upik' => $id_upik, ))->row();
  }
  
   function set_freze($id)
    {
        //$user_input = $_SESSION['userid'];

        $sql = "
			update tbl_user set freze = '1' where id_user IN(" . $id . ")
       ";

        return $this->db->query($sql, array($id));
    }

    function set_unfreze($id)
    {
        // $user_input = '';

        $sql = "
			update tbl_user set freze = '0' where id_user IN(" . $id . ")
       ";

        return $this->db->query($sql, array($id));
    }
}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-09 06:17:03 */
/* http://harviacode.com */
